// SPDX-FileCopyrightText: ©  Basil Peace
// SPDX-License-Identifier: CC0-1.0
= Source Metadata File Format Specification $$VERSION$$

:sectnums:
:xrefstyle: short

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT",
"RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted
as described in https://tools.ietf.org/html/rfc2119[RFC 2119].

Terms "`source code`", "`object code`", "`original work`", "`modified version`" in this document
are to be interpreted the same way as by https://www.gnu.org/licenses/gpl-3.0.en.html#section1[GPL 3.0].

== Purpose

_This section is non-normative._

Source Metadata file provides common information such as homepage, copyright, applied licenses
about software project in its "`source code`" form.

It can be easily created by hands and read by both tools and humans.

Source Metadata can also be used for sources of art works, including fonts.

Source Metadata file is language/tool-agnostic. It generally doesn't describe non-source forms (object code)
of software. However, build tools are encouraged to use Source Metadata to describe produced artifacts.

== Getting Started

A valid Source Metadata file may look like this:

[source,yaml]
----
include::examples/valid/example.yaml[]
----

== File Format

A Source Metadata file MUST be a https://yaml.org/spec/1.2/spec.html[YAML 1.2] formatted text file.
It MUST be encoded in UTF-8 without byte order mark.
// TOTEST

== Value Types and Field Names

// TODO: Currently I don't check (and convert) fields in custom maps

[start=0]
. Rules listed in this section are applied to fields of root document
and fields on all levels of nested mappings as well.

. /* TODO */ For fields referencing file this specification or specifications of extensions MAY prescribe
separate sibling field with additional `_content_type` suffix.
If such field is provided then its value MUST contain MIME type for the file
and MAY contain its charset. For example, `text/asciidoc` or `text/markdown; charset=UTF-8`.
+
If this field or charset are not provided then charset MAY be detected
from BOM mark or other methods appropriate for the format.
Default value is detection is not implemented or was not successful of UTF-8.
+
If this field is not provided then MIME type MAY be detected from extension of the file name.
If file name has no extension then MIME type MUST be default `text/plain`.
+
If specification doesn't prescribe such separate field
then content type of file MUST be `text/plain` and charset MUST be UTF-8.

. Types of predefined fields are prescribed by this specification and specifications of extensions.
+
// https://github.com/asciidoctor/asciidoctor/issues/3253
// TODO xref:Unknown_fields[xrefstyle="short"] */
Types of unknown fields mentioned in article 4 of <<_extensions_and_extra_fields>>
MUST be determined according to YAML rules.

. All field names are case-sensitive, however, use of lower snake case is RECOMMENDED.

include::build/docs/sourcemetadata.schema.asciidoc[leveloffset=+1]

=== General Fields

. `status`: ...
If `version` field is provided and not matched TODO

. `long_description_file_content_type`:

. `changelog_file_content_type`:

. `release_notes_file_content_type`:

=== Fields to specify version control system (VCS)

These fields provide a simple way to reference files stored in a version control
system. There are many VCS tools such as CVS, Subversion, Git, ClearCase and GNU
Arch. Accurate addressing of a file or directory revision in each tool in a
uniform way may not be possible. Some tools may require access control via
user/password or certificate and this information should not be stored in an
ABOUT file. This extension defines the 'vcs' field extension prefix and a few
common fields to handle the diversity of ways that VCS tools reference files and
directories under version control:

// TODO: web-browseable URL
// TODO: developer_connection_url


If Source Metadata file is located in directory managed by SCM then:

. Implementation MAY use SCM data about remote repository instead of data specified in Source Metadata file.

. Implementation MAY reset `is_modified` field to true whenever SCM data about remote repository doesn't match data
from Source Metadata file (fork detection).

== Extensions and Extra Fields

. You MAY create own extensions of this specification. All fields of an extension MUST have
short prefix to distinguish them from the standard fields. You SHOULD provide documentation for
such extension and create or extend existing tools to support it.
+
Names of fields of any extension MUST meet <<_value_types_and_field_names>> requirements.

. Extensions MAY specify new fields as for both root document and for nested mappings on any level.

. Extensions SHOULD group interconnected fields to mappings.

. [[Unknown_fields]] Implementation MUST either ignore any fields with unknown names or parse them
as _extra_ dynamically-typed fields.

== Specification Versions

. Version of Source Metadata specification used to create a file MUST be mentioned
in `spec_version` field. TODO

. This specification is versioned according to SemVer 2.0.0.

. Implementation of any version of this specification SHOULD be able to read files
written with any previous major version of this specification.

. Implementation of any version of this specification MUST report an error when it parses Source Metadata
with major version of `spec_version` greater than major version of implemented version.

== File Name and Location

Source Metadata file MUST be stored in project's source code.

By default Source Metadata file MUST be stored in the root directory of project sources
and MUST have the name `sourcemetadata.yaml`.

== Additional Requirements

. Project sources MUST have license files placed
according to https://reuse.software/spec/#license-files[REUSE Specification 3.0].

. Implementation MUST provide mapping of licenses and their files.

. Implementation MUST also provide mapping of licenses and their names, URLs and comments.
To achieve this, in addition to REUSE Practices:

// TODO: `Valid` prefix ?
.. Non-SPDX-listed licenses MUST have adjacent file of the same name with the additional `.license` extension.
For example, `LicenseRef-CustomLicense.txt.license`. Such file is called `.license` companion file.
File MUST have the same format as specified by REUSE Specification for comment headers.

.. `.license` companion file MUST have tag `SPDX-LicenseName` with content described by
Section https://spdx.org/spdx-specification-21-web-version#h.19c6y18[6.3]
of SPDX Specification 2.1.

.. `.license` companion file MAY have the following tags:
+
--
* `SPDX-LicenseCrossReference`: URL to the license text

* `SPDX-LicenseComment`: any general comments about the license
--
+
described by Sections https://spdx.org/spdx-specification-21-web-version#h.3tbugp1[6.4] and
https://spdx.org/spdx-specification-21-web-version#h.28h4qwu[6.5]
of SPDX Specification 2.1 respectively.

.. For SPDX-listed licenses, if `.license` companion file exists, it MUST NOT contain tags specified above.
Implementation MUST use values of `SPDX-LicenseName`, `SPDX-LicenseCrossReference` and `SPDX-LicenseComments`
tags from SPDX license list.
