// SPDX-Copyright: ©  Basil Peace
// SPDX-License-Identifier: CC0-1.0
= Source Metadata File Format Specification 0.1.0

:sectnums:
:xrefstyle: short

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT",
"RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted
as described in https://tools.ietf.org/html/rfc2119[RFC 2119].

== Purpose

_This section is non-normative._

Source Metadata file provides common information such as homepage, copyright, applied licenses
about software project in its "`source code`" form.

It can be easily created by hands and read by both tools and humans.

Source Metadata can also be used for sources of art works, including fonts.

Source Metadata file is language/tool-agnostic. It generally doesn't describe non-source forms (object code)
of software. However, build tools are encouraged to use Source Metadata to describe produced artifacts.

Terms "`source code`" and "`object code`" in this section are to be interpreted the same way
as by https://www.gnu.org/licenses/gpl-3.0.en.html#section1[GPL 3.0].

== Getting Started

A valid Source Metadata file may look like this:

```yaml
name: gradle-sourcemetadata-plugin
spec_version: 1.0.0
version: 1.2.3
versioning_schema: semver-2.0.0
description: |-
  Parsing Source Metadata files from Java and Gradle
copyright: ©  Basil Peace
copyright_email: grv87@yandex.ru
license_expression: GPL-3.0-or-later OR LicenseRef-Proprietary
licenses:
  GPL-3.0-or-later:
    distribution: manual
  LicenseRef-Proprietary:
    distribution: repo
is_internal: false
scm_url: scm:git:https://github.com/FIDATA/gradle-metadata-plugin
organization:
  name: FIDATA
  url: https://fidata.org/
developers:
  grv87:
    name: Basil Peace
    organization: FIDATA
    roles:
      - author
      - owner
      - developer
    timezone: Europe/Moscow
    properties:
      github: grv87
      twitter: grv87
issue_management:
  system: GitHub
  url: https://github.com/FIDATA/gradle-metadata-plugin/issues
ci_management:
  system: Jenkins
  url: https://jenkins.fidata.org/job/Github/job/gradle-metadata-plugin/
keywords:
  - project
  - metadata
  - info
  - contacts
  - license
```

== File Format

A Source Metadata file MUST be a https://yaml.org/spec/1.2/spec.html[YAML 1.2] formatted text file.
It MUST be encoded in UTF-8 without byte order mark.
// TOTEST

== Value Types and Field Names

// TODO: Currently I don't check (and convert) fields in custom maps

[start=0]
. Rules listed in this section are applied to fields of root document
and fields on all levels of nested mappings as well.

. Field referencing file MUST have name `file` or suffix `_file`.
+
File path MUST be relative to the directory containing Source Metadata file.

. /* TODO */ For fields referencing file this specification or specifications of extensions MAY prescribe
separate sibling field with additional `_content_type` suffix.
If such field is provided then its value MUST contain MIME type for the file
and MAY contain its charset. For example, `text/asciidoc` or `text/markdown; charset=UTF-8`.
+
If this field or charset are not provided then charset MAY be detected
from BOM mark or other methods appropriate for the format.
Default value is detection is not implemented or was not successful of UTF-8.
+
If this field is not provided then MIME type MAY be detected from extension of the file name.
If file name has no extension then MIME type MUST be default `text/plain`.
+
If specification doesn't prescribe such separate field
then content type of file MUST be `text/plain` and charset MUST be UTF-8.

. Field containing URL MUST have name `url` or suffix `_url`.

. Field containing email address MUST have name `email` or suffix `_email`.

. Field containing physical address MUST have name `address` or suffix `_address`.

. Field containing boolean flags MUST have `is_` prefix.

. Field containing sequences of files, URLs, emails or physical addresses MUST have names `files`, `urls`,
`emails`, `addresses` or suffixes `_files`, `_urls`, `_emails`, `_addresses` respectively.
Values in sequences SHOULD be unique.

. All other fields not mentioned in articles 1-7 MAY be either strings, sequences of strings,
mappings or sequences of mappings.
+
Types of predefined fields are prescribed by this specification and specifications of extensions.
+
// https://github.com/asciidoctor/asciidoctor/issues/3253
// TODO xref:Unknown_fields[xrefstyle="short"] */
Types of unknown fields mentioned in article 4 of <<_extensions_and_extra_fields>>
MUST be determined according to YAML rules.

. All field names are case-sensitive, however, use of lower snake case is RECOMMENDED.

== Standard Fields

=== Mandatory Fields

Fields `name` and `spec_version` MUST be present.

=== General Fields

. `name`: programmatic name of the project

. `title`: human-readable name of the project

. `status`: ...
If `version` field is provided and not matched TODO

. `version`: Version of the project

// TOTEST
. `versioning_schema`: Versioning schema used for the project ``version``'s.
Must be a valid https://versionmeta.org/[Version Meta] URI.
For example, `SemVer.2.0.0`

. `description`: Project description, as a short text.

. `long_description_file`:

. `long_description_file_content_type`:

. `homepage_url`: URL to the homepage of the project.

. `documentation_url`: separate URL to the documentation for the project.
By default it equals to the value of `homepage_url` field

. `wiki_url`: separate URL to the project wiki.

. `changelog_file`: Changelog file for the project.

. `changelog_file_content_type`:

. `changelog_url`:

. `release_notes_file`: Release notes for the project.

. `release_notes_file_content_type`:

. `icon_url`: an URL for the project icon. Icon MUST have size 64x64 pixels and MUST have transparent background

. `languages`: sequence of https://tools.ietf.org/html/bcp47[BCP 47] language tags
describing human languages explicitly supported by the project.
For example, in which languages project messages are provided.
Default value is neutral language (empty language tag).
If this sequence contains more than one item then the first item MUST be original (primary) project language.

. `issue_management`: mapping of the following fields:

.. `type`:

.. `url`:

. `ci_management`: mapping of the following fields:

.. `type`:

.. `url`:

. `mailing_lists`: sequence of mappings of the following fields:

.. `subscribe_email`, `post_email`, `unsubscribe_email`: email addresses which are used for performing
the relative actions

.. `archive_urls`: sequence of URLs of the archive of old mailing list emails, if one exists.
If this sequence contains more than one item then the first item MUST be interpreted as original URL
and remaining MUST be interpreted as mirrors.

. `inception_year`: the year of the project's inception, specified with 4 digits in Gregorian calendar

. `keywords`: TODO

. `cert_chain_file`: The certificate chain used to sign project's object code

. `cert_chain_url`: The certificate chain used to sign project's object code

=== Copyright and Licensing Fields

. `copyright`: Copyright statement for the project, without email and address

. `copyright_email`:

. `copyright_address`:

. `notice_file`: Legal notice or credits for the project,
for example, `NOTICE` file specified by Apache-2.0 license

. `license_expression`: The SPDX license expression that apply to the project

. `distribution_under_licenses`: mapping having disjuncts from `license_expression` as keys
and strings `repo` or `manual` as values.
+
This describes how the project may be legally distributed under which license.
+
`repo` means project object code MAY be downloaded from a package repository.
+
`manual` means it MUST be manually installed.

. `is_modified`: Whether the project is a modified original work (a fork).
By default it is false

. `is_internal`: Whether the project is used internal only (releases are not public).
By default it is false

=== Organization, Author, Developer and Contributor Fields

. author: Name of the organization(s) or person(s) that authored the project.

=== Fields to specify version control system (VCS)

These fields provide a simple way to reference files stored in a version control
system. There are many VCS tools such as CVS, Subversion, Git, ClearCase and GNU
Arch. Accurate addressing of a file or directory revision in each tool in a
uniform way may not be possible. Some tools may require access control via
user/password or certificate and this information should not be stored in an
ABOUT file. This extension defines the 'vcs' field extension prefix and a few
common fields to handle the diversity of ways that VCS tools reference files and
directories under version control:

* `vcs_url`:

. `vcs_tool`: VCS tool such as git, svn, cvs, etc.

. `vcs_repository`: Typically a URL or some other identifier used by a VCS tool to
  point to a repository such as an SVN or Git repository URL.

. `vcs_path`: Path used by a particular VCS tool to point to a file, directory or
  module inside a repository.

. `vcs_tag`: tag name or path used by a particular VCS tool.

. `vcs_branch`: branch name or path used by a particular VCS tool.

. `vcs_revision`: revision identifier such as a revision hash or version number.

// TODO: web-browseable URL
// TODO: developer_connection_url


Some examples for using the `vcs_*` extension fields include:

      vcs_tool: svn
      vcs_repository: http://svn.code.sf.net/p/inkscape/code/inkscape_project/
      vcs_path: trunk/inkscape_planet/
      vcs_revision: 22886

or:

      vcs_tool: git
      vcs_repository: git://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git
      vcs_path: tools/lib/traceevent
      vcs_revision: b59958d90b3e75a3b66cd311661535f94f5be4d1

If Source Metadata file is located in directory managed by SCM then:

. Implementation MAY use SCM data about remote repository instead of data specified in Source Metadata file

. Implementation MAY reset `modified` field to true whenever SCM data about remote repository doesn't match data
from Source Metadata file (fork detection)

== Extensions and Extra Fields

. You MAY create own extensions of this specification. All fields of an extension MUST have
short prefix to distinguish them from the standard fields. You SHOULD provide documentation for
such extension and create or extend existing tools to support it.
+
Names of fields of any extension MUST meet <<_value_types_and_field_names>> requirements.

. Extensions MAY specify new fields as for both root document and for nested mappings on any level.

. Extensions SHOULD group interconnected fields to mappings.

. [[Unknown_fields]] Implementation MUST either ignore any fields with unknown names or parse them
as _extra_ dynamically-typed fields.

== Specification Versions

. Version of Source Metadata specification used to create a file MUST be mentioned
in `spec_version` field.

. This specification is versioned according to SemVer 2.0.0.

. Implementation of any version of this specification SHOULD be able to read files
written with any previous major version of this specification.

. Implementation of any version of this specification MUST report an error when it parses Source Metadata
with major version of `spec_version` greater than major version of implemented version.

== File Name and Location

Source Metadata file MUST be stored in project's source code.

By default Source Metadata file MUST be stored in the root directory of project sources
and MUST have the name `sourcemetadata.yaml`.

== Additional Requirements

Project sources MUST have license files placed and tagged according to
https://reuse.software/practices/2.0/index.html#1-provide-the-exact-text-of-each-license-used[Section 1
of REUSE practices].

Implementation MUST provide mapping of licenses and their files.

Implementation MUST also provide mapping of licenses and their names, URLs and comments.
To achieve this, in addition to REUSE Practices:

// TODO: `Valid` prefix ?
1. Headers of non-SPDX-listed licenses MUST have SPDX tag `LicenseName` described by
Section https://spdx.org/spdx-specification-21-web-version#h.19c6y18[6.3]
of SPDX Specification 2.1.

2. Headers of non-SPDX-listed licenses MAY have the following SPDX tags:
+
--
 * `LicenseCrossReference`: URL to the license text

 * `LicenseComment`
--
+
described by Sections https://spdx.org/spdx-specification-21-web-version#h.3tbugp1[6.4] and
https://spdx.org/spdx-specification-21-web-version#h.28h4qwu[6.5]
of SPDX Specification 2.1 respectively.

3. For SPDX-listed licenses values of `LicenseName`, `LicenseCrossReference` and `LicenseComments` tags SHOULD be got
from SPDX license list.

== Acknowledgments and Differences with Other Existing Solutions

* The idea goes to

* Polyglot Maven

* ClearlyDefined
